# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [3]:
### [your code here]
print(np.version.version)

2.2.5


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [4]:
### [your code here]
a = np.random.randint(10, size=(2, 3, 5))

In [5]:
aa = np.random.random(size=(2, 3, 5))
aa

array([[[0.73773464, 0.84147322, 0.95380339, 0.19273015, 0.01911876],
        [0.21828496, 0.79798639, 0.54946885, 0.05771115, 0.98940753],
        [0.87341576, 0.1208124 , 0.05345454, 0.80709554, 0.99384958]],

       [[0.7146427 , 0.73889584, 0.58263739, 0.1552977 , 0.32963236],
        [0.95065779, 0.57469346, 0.49023791, 0.85522008, 0.89872488],
        [0.42587058, 0.09629422, 0.61043993, 0.30656913, 0.7780495 ]]])

In [6]:
aaa = np.random.rand(2,3,5)
aaa

array([[[0.80912459, 0.16359662, 0.72073499, 0.12707715, 0.08843276],
        [0.2160909 , 0.56050739, 0.33386354, 0.6597112 , 0.2814734 ],
        [0.77394185, 0.42737524, 0.3991704 , 0.14279601, 0.20689268]],

       [[0.77327668, 0.59291054, 0.25551097, 0.78261312, 0.26959345],
        [0.00854966, 0.07189779, 0.74979198, 0.26445544, 0.78398933],
        [0.98946892, 0.2181205 , 0.06410375, 0.67730014, 0.84130067]]])


### 4. Print a.


In [7]:
### [your code here]
print(a)

[[[6 1 0 0 8]
  [2 7 5 5 0]
  [5 3 6 0 1]]

 [[0 8 8 2 4]
  [3 3 0 4 8]
  [3 9 5 7 0]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"



### 6. Print b.


In [8]:
### [your code here]
b = np.ones((5, 2, 3))

In [9]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [10]:
size_comparison = (np.size(a)) == (np.size(b))
size_comparison

True


### 8. Are you able to add a and b? Why or why not?


In [11]:
### [your code here]
ab_add = np.add(a, b)
ab_add

#not possible: ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [13]:
### [your code here]
c = np.transpose(b, axes=(1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [15]:
### [your code here]
d = a + c
d
#it works because both a and c have the same shape.

array([[[ 7.,  2.,  1.,  1.,  9.],
        [ 3.,  8.,  6.,  6.,  1.],
        [ 6.,  4.,  7.,  1.,  2.]],

       [[ 1.,  9.,  9.,  3.,  5.],
        [ 4.,  4.,  1.,  5.,  9.],
        [ 4., 10.,  6.,  8.,  1.]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [16]:
### [your code here]
print(a)
print(d)

#the array "d" adds 1 to each element from array "a", because the array "b" is all ones. a(0,0) adds c(0,0) and this becomes c(0,0)

[[[6 1 0 0 8]
  [2 7 5 5 0]
  [5 3 6 0 1]]

 [[0 8 8 2 4]
  [3 3 0 4 8]
  [3 9 5 7 0]]]
[[[ 7.  2.  1.  1.  9.]
  [ 3.  8.  6.  6.  1.]
  [ 6.  4.  7.  1.  2.]]

 [[ 1.  9.  9.  3.  5.]
  [ 4.  4.  1.  5.  9.]
  [ 4. 10.  6.  8.  1.]]]



### 12. Multiply a and c. Assign the result to e.


In [17]:
### [your code here]
e = a * c
e

array([[[6., 1., 0., 0., 8.],
        [2., 7., 5., 5., 0.],
        [5., 3., 6., 0., 1.]],

       [[0., 8., 8., 2., 4.],
        [3., 3., 0., 4., 8.],
        [3., 9., 5., 7., 0.]]])



### 13. Does e equal to a? Why or why not?


In [18]:
### [your code here]
equal = e == a
equal

#it is equal because c is all ones, which means you multiply each element of a by 1.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [19]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)
print(d)

10.0
1.0
4.766666666666667
[[[ 7.  2.  1.  1.  9.]
  [ 3.  8.  6.  6.  1.]
  [ 6.  4.  7.  1.  2.]]

 [[ 1.  9.  9.  3.  5.]
  [ 4.  4.  1.  5.  9.]
  [ 4. 10.  6.  8.  1.]]]



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [20]:
### [your code here]
f = np.empty([2, 3, 5])





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [22]:
for row_i, row in enumerate(d[0]):
    for col_i, item in enumerate(row):
        if d_mean > item > d_min:
            f[0, row_i, col_i] = 25
        elif d_mean == item:
            f[0,row_i, col_i] = 50
        elif d_max == item:
            f[0,row_i, col_i] = 100
        elif d_min == item:
            f[0,row_i, col_i] = 0
        else:
            f[0,row_i, col_i] = 75

for row_i, row in enumerate(d[1]):
    for col_i, item in enumerate(row):
        if d_mean > item > d_min:
            f[1,row_i, col_i] = 25
        elif d_mean == item:
            f[1,row_i, col_i] = 50
        elif d_max == item:
            f[1,row_i, col_i] = 100
        elif d_min == item:
            f[1,row_i, col_i] = 0
        else:
            f[1,row_i, col_i] = 75
print(f)

[[[ 75.  25.   0.   0.  75.]
  [ 25.  75.  75.  75.   0.]
  [ 75.  25.  75.   0.  25.]]

 [[  0.  75.  75.  25.  75.]
  [ 25.  25.   0.  75.  75.]
  [ 25. 100.  75.  75.   0.]]]


In [21]:
for layer_i, layer in enumerate(d):
    for row_i, row in enumerate(layer):
        for col_i, item in enumerate(row):
            if d_mean > item > d_min:
                f[layer_i, row_i, col_i] = 25
            elif d_mean == item:
                f[layer_i, row_i, col_i] = 50
            elif d_max == item:
                f[layer_i, row_i, col_i] = 100
            elif d_min == item:
                f[layer_i, row_i, col_i] = 0
            else:
                f[layer_i, row_i, col_i] = 75

print(f)
print(d)

[[[ 75.  25.   0.   0.  75.]
  [ 25.  75.  75.  75.   0.]
  [ 75.  25.  75.   0.  25.]]

 [[  0.  75.  75.  25.  75.]
  [ 25.  25.   0.  75.  75.]
  [ 25. 100.  75.  75.   0.]]]
[[[ 7.  2.  1.  1.  9.]
  [ 3.  8.  6.  6.  1.]
  [ 6.  4.  7.  1.  2.]]

 [[ 1.  9.  9.  3.  5.]
  [ 4.  4.  1.  5.  9.]
  [ 4. 10.  6.  8.  1.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [23]:
### [your code here]
print(d)
print(f)

[[[ 7.  2.  1.  1.  9.]
  [ 3.  8.  6.  6.  1.]
  [ 6.  4.  7.  1.  2.]]

 [[ 1.  9.  9.  3.  5.]
  [ 4.  4.  1.  5.  9.]
  [ 4. 10.  6.  8.  1.]]]
[[[ 75.  25.   0.   0.  75.]
  [ 25.  75.  75.  75.   0.]
  [ 75.  25.  75.   0.  25.]]

 [[  0.  75.  75.  25.  75.]
  [ 25.  25.   0.  75.  75.]
  [ 25. 100.  75.  75.   0.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [30]:
### [your code here]
g = np.empty([2, 3, 5], dtype=str)

for layer_i, layer in enumerate(d):
    for row_i, row in enumerate(layer):
        for col_i, item in enumerate(row):
            if d_mean > item > d_min:
                g[layer_i, row_i, col_i] = "B"
            elif d_mean == item:
                g[layer_i, row_i, col_i] = "C"
            elif d_max == item:
                g[layer_i, row_i, col_i] = "E"
            elif d_min == item:
                g[layer_i, row_i, col_i] = "A"
            else:
                g[layer_i, row_i, col_i] = "D"

In [32]:
print(g)

[[['D' 'B' 'A' 'A' 'D']
  ['B' 'D' 'D' 'D' 'A']
  ['D' 'B' 'D' 'A' 'B']]

 [['A' 'D' 'D' 'B' 'D']
  ['B' 'B' 'A' 'D' 'D']
  ['B' 'E' 'D' 'D' 'A']]]
